### PR TITLE
modified util file to use the functions in avenger.py

### PR DESCRIPTION
**Pull request by asghimire**
modified util file to use the functions in avenger.py

### CODE REVIEW

**Comment by asghimire** [comment]
Added avenger.py file that has methods for all the fields in avenger.csv file
Made some changes to util.py file so that its functions can be used in avenger.py file.
Please review the changes.
Thanks

**Comment by pokhalan** [comment]
Looks like there is some conflict with util.py file.

**Review by pokhalan — APPROVED** [review]
Avenger can be merged, however looks like util.py file needs some review. Conflict needs to be resolved.

**Review by emprorgh — APPROVED** [review]
Looks good. There is no conflict. This branch can be merged.

**Comment by asghimire** [comment]
Merged pull request to master.

**Pull request merged**
